// languages for the code editor
// any better way to do this?
export const languages = [
    { id: 1, name: 'JavaScript', slug: 'javascript' },
    { id: 2, name: 'TypeScript', slug: 'typescript' },
    { id: 3, name: 'Python', slug: 'python' },
    { id: 4, name: 'Java', slug: 'java' },
    { id: 5, name: 'C#', slug: 'csharp' },
    { id: 6, name: 'C++', slug: 'cpp' },
    { id: 7, name: 'C', slug: 'c' },
    { id: 8, name: 'Go', slug: 'go' },
    { id: 9, name: 'Rust', slug: 'rust' },
    { id: 10, name: 'PHP', slug: 'php' },
    { id: 11, name: 'Ruby', slug: 'ruby' },
    { id: 12, name: 'Swift', slug: 'swift' },
    { id: 13, name: 'Kotlin', slug: 'kotlin' },
    { id: 14, name: 'Dart', slug: 'dart' },
    { id: 15, name: 'HTML', slug: 'html' },
    { id: 16, name: 'CSS', slug: 'css' },
    { id: 17, name: 'SQL', slug: 'sql' },
    { id: 18, name: 'Shell', slug: 'shell' },
    { id: 19, name: 'PowerShell', slug: 'powershell' },
    { id: 20, name: 'YAML', slug: 'yaml' },
    { id: 21, name: 'JSON', slug: 'json' },
    { id: 22, name: 'Markdown', slug: 'markdown' },
    { id: 23, name: 'Dockerfile', slug: 'dockerfile' },
    { id: 24, name: 'Plain Text', slug: 'text' }
];

export const LANGUAGE_COLORS = {
  javascript: "#f7df1e",
  typescript: "#3178c6",
  python: "#3572A5",
  java: "#b07219",
  "c++": "#00599c",
  csharp: "#178600",
  php: "#4F5D95",
  ruby: "#701516",
  go: "#00ADD8",
  rust: "#dea584",
  swift: "#ffac45",
  kotlin: "#A97BFF",
  dart: "#00B4AB",
  html: "#e34c26",
  css: "#563d7c",
  scss: "#c6538c",
  sql: "#e38c00",
  json: "#cbcb41",
  yaml: "#cb171e",
  markdown: "#083fa1",
  bash: "#89e051",
  powershell: "#012456",
  dockerfile: "#384d54",
  xml: "#0060ac",
  plaintext: "#999999"
};